name: 'active-active mode'

on:
  push:
    branches: [ "main" ]
  pull_request:
  

jobs:
  build:
    name: active-active mode
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-python@v2
      - uses: actions/setup-go@v3
        with:
             go-version: '>=1.18.0'
      - run: sudo apt-get update
      - run: sudo apt-get -y install iperf iproute2 nodejs socat ethtool lksctp-tools
      - run: |
             cd cicd/activemode-lb/
             ./config.sh
             ./validation.sh
             ./rmconfig.sh
             cd -
